// next-env.d.ts (gitignored, auto-generated by `next build`/`next dev`)
// normally supplies this declaration via its reference to
// next/image-types/global. CI runs `npm run typecheck` before
// `npm run build`, so next-env.d.ts does not exist yet at that point —
// this committed, self-contained declaration does not depend on
// generation order.
declare module "*.png" {
  const value: {
    src: string;
    height: number;
    width: number;
    blurDataURL?: string;
    blurWidth?: number;
    blurHeight?: number;
  };
  export default value;
}

declare module "*.jpg" {
  const value: {
    src: string;
    height: number;
    width: number;
    blurDataURL?: string;
    blurWidth?: number;
    blurHeight?: number;
  };
  export default value;
}

declare module "*.jpeg" {
  const value: {
    src: string;
    height: number;
    width: number;
    blurDataURL?: string;
    blurWidth?: number;
    blurHeight?: number;
  };
  export default value;
}
